### ISSUE TITLE
Modifying "get_categories_and_urls" in order to just pull a single category?

### ISSUE THREAD

**Issue by nishanpanag** [lmeninato/GoFundMe#2]
First off, wanted to thank you for writing such great code! I'm super interested in gofundme so as someone relatively new to python this is super helpful.

I was wondering if you know of a way to modify this in order to only scrape the first category (medical) of campaign url's? 

Thanks so much!!!

**Comment by lmeninato** [comment]
Hi @nishanpanag. Thanks for your interest in this project! To modify the scraping you would need to change line 40 in that file (`categories_urls = list(map(lambda x:{x:'https://www.gofundme.com/discover/{}-fundraiser'.format(x.lower())}, all_cats))
`) It sounds like you'd want to filter that list to contain just the categories you are interested in. BTW I haven't looked at this project closely in a while, so especially some of the HTML elements I grab with BeautifulSoup might need to be looked at more closely.
